### ISSUE TITLE
Record loading issue

### ISSUE THREAD

**Issue by marinadistefano** [clingen-data-model/clingen-gene-tracker#10] opened 2020-02-27 14:27 UTC
Sometimes when I click into a record from the gene list (either the whole list or my dashboard) the information from the record does not populate and I cannot edit it. This is remedied when I search for the gene specifically and edit it. This is also done in Chrome.

**Comment by yugen** [comment] 2020-02-27 15:20
Thanks for reporting the issue @marinadistefano.  I haven't been able to reproduce this yet.  Would you mind providing the following information so I can try to narrow down the conditions?
1. A gene on which you've experienced this
2. Which browser you're using 

Thanks for you help.

**Comment by yugen** [comment] 2020-02-27 15:21
Thanks for reporting the issue @marinadistefano.  I haven't been able to reproduce this yet.  Would you mind providing the following information so I can try to narrow down the conditions?
1. A gene on which you've experienced this
2. Which browser you're using 

Thanks for you help.

**Comment by marinadistefano** [comment] 2020-02-27 15:29
As an update, I've found  if I reload the page, it gives me a security error and then loads the information. 

It's happened with all of the records I've tried, but one example is ELMOD3 in the HL GCEP. If you need me to get on a zoom and show you, just let me know.

**Comment by yugen** [comment] 2020-02-27 16:29
I still can't reproduce the problem you're having so if you wouldn't mind dong a zoom call that would be great.  I'm free until 1 or we can schedule a time for tomorrow.

**Comment by marinadistefano** [comment] 2020-02-27 17:46
Here's my personal zoom if you want to do it now:

https://broadinstitute.zoom.us/j/851191638

**Comment by marinadistefano** [comment] 2020-02-27 17:48
If not, we can set up for tomorrow.

**Comment by yugen** [comment] 2020-03-02 15:36
hi @marinadistefano.  This issue should be fixed now.  I'm going to close the ticket, but please reopen if continue to experience the problem.

Thanks!

**Closed by yugen** 2020-03-02 15:36 UTC
Labels: bug
